routes:
  /:
    controller: channel
    template: home
  /newsletters/:
    controller: channel
    filter: primary_tag:newsletter
    data:
      page: page.newsletters
    template: page-newsletters
  /podcasts/:
    controller: channel
    filter: primary_tag:podcast
    data:
      page: page.podcasts
    template: page-podcasts
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade

collections:
  /archive/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
